// This file is auto-generated by `amplify push` — do not edit manually.
// Run: amplify init → amplify add api → amplify push
const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_appsync_graphqlEndpoint: '',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: '',
};
export default awsmobile;
